#+TITLE: =sax=

* Overview and usage

  !README is outdated!

  =sax= (scissor in Swedish) is an intuitive way to find your beloved shell commands.
  =sax= is somewhat similar to =history | grep <COMMAND>= but provides you with context.
  Instead of having =~/.bash_history= as the source you have your own org document.

  Here is an example org document with a couple of commands. This is our example source.

  #+BEGIN_SRC org
    ,#+TITLE: My useful shell commands

    ,* tar
    ,** Compress entire directory or a single file

       https://www.howtogeek.com/248780/how-to-compress-and-extract-files-using-the-tar-command-on-linux/

       ,#+BEGIN_SRC shell
         tar -czvf name-of-archive.tar.gz /path/to/directory-or-file
       ,#+END_SRC

    ,** Extract archive

       ,#+BEGIN_SRC shell
         tar -xzvf archive.tar.gz
       ,#+END_SRC

    ,* user management
    ,** create new user

       ,#+BEGIN_SRC shell
        useradd -m -g users -G wheel,video <USER>
       ,#+END_SRC

    ,* random top heading
    ,** random sub heading
    ,*** some command

        This is not a real command. Just here to show that =sax= finds this section.

        ,#+BEGIN_SRC shell
          some command where tar is used
        ,#+END_SRC
  #+END_SRC

  Example usage:

  #+BEGIN_SRC shell :results output code
    ~ $ sax tar
    3 * tar
    4 ** Compress entire directory or a single file
    5
    6    https://www.howtogeek.com/248780/how-to-compress-and-extract-files-using-the-tar-command-on-linux/
    7
    8    #+BEGIN_SRC shell
    9      tar -czvf name-of-archive.tar.gz /path/to/directory-or-file
    10    #+END_SRC
    11
    12 ** Extract archive
    13
    14    #+BEGIN_SRC shell
    15      tar -xzvf archive.tar.gz
    16    #+END_SRC
    17
    27 *** Some command
    28
    29     This is not a real command. Just here to show how that =sax= finds this section.
    30
    31     #+BEGIN_SRC shell
    32       some command where tar is used
    33     #+END_SRC
    ~ $ sax tar 15 | wl-copy      # The line nr 15 is now trimmed and added to clipboard
    ~ $ tar -xzvf archive.tar.gz  # Command is pasted back in the shell from clipboard
  #+END_SRC

  In the showcase we look for =tar= commands as I never can remember the correct arguments
  to extract an archive. We get a few hits. One of them is in a places where =tar= is used
  together with another command. But the major one is a heading matching =tar= and all of
  its subsections. On line 15 is the command I am looking for. By running =sax= again with
  the same argument + the line nr it returns that line. Trimmed and without a trailing
  newline. This makes it perfect to pipe into a clipboard.

  If a heading contains a match. Its returned together with all of its sub sections.

  If a match is found in a non heading line. Only that section is provided.

  =sax= does only 2 things. It looks for a pattern and tries to provide matches together
  with their context. And it can provide a single line from a set of matches.

* Install

  Clone the repo to some place, in the examples it's cloned to: =~/git/sax=.

  Set environment variable so you can reach =sax=. Point =SAXFILE= to your org
  file.

  #+BEGIN_SRC shell :results output code
    export PATH="$PATH:$HOME/git/sax/"
    export AWKPATH="$AWKPATH:$HOME/git/sax/"
    export SAXFILE="$HOME/org-documents/shell-commands.org"
    export SAXPIPE=wl-copy
  #+END_SRC

  You may need to logout and login again to update environment variables. Or
  source your =.bashrc= using: =source ~/.bashrc=
