#+TITLE: =sax=

* Overview and usage

  =sax= (scissor in Swedish) is an intuitive way to find and execute your beloved shell
  commands. =sax= is simillar to =history | grep <COMMAND>= and =!<HISTORY LINE NR>= but
  provides you with a context. Instead of having =~/.bash_history= as the source you have
  your own org document.

  Here is an example org document with a couple of commands.

  #+BEGIN_SRC org
    ,#+TITLE: My useful shell commands

    ,* tar
    ,** Compress entire directory or a single file

       https://www.howtogeek.com/248780/how-to-compress-and-extract-files-using-the-tar-command-on-linux/

       ,#+BEGIN_SRC shell
         tar -czvf name-of-archive.tar.gz /path/to/directory-or-file
       ,#+END_SRC

    ,** Extract archive

       ,#+BEGIN_SRC shell
         tar -xzvf archive.tar.gz
       ,#+END_SRC

    ,* user management
    ,** create new user

       ,#+BEGIN_SRC shell
        useradd -m -g users -G wheel,video <USER>
       ,#+END_SRC

    ,* top heading
    ,** subheading
    ,*** Some command

        This is not a real command. Just here to show how that =sax= finds this section.

        ,#+BEGIN_SRC shell
          some command where tar is used
        ,#+END_SRC
  #+END_SRC

  Usage:

  #+BEGIN_SRC shell :results output code
    ~ $ sax tar
    3 * tar
    4 ** Compress entire directory or a single file
    5
    6    https://www.howtogeek.com/248780/how-to-compress-and-extract-files-using-the-tar-command-on-linux/
    7
    8    #+BEGIN_SRC shell
    9      tar -czvf name-of-archive.tar.gz /path/to/directory-or-file
    10    #+END_SRC
    11
    12 ** Extract archive
    13
    14    #+BEGIN_SRC shell
    15      tar -xzvf archive.tar.gz
    16    #+END_SRC
    17
    27 *** Some command
    28
    29     This is not a real command. Just here to show how that =sax= finds this section.
    30
    31     #+BEGIN_SRC shell
    32       some command where tar is used
    33     #+END_SRC
    ~ $ sax tar 15 | wl-copy      # The line nr 15 is now trimmed and added to clipboard
    ~ $ tar -xzvf archive.tar.gz  # Command is pasted back in the shell
  #+END_SRC

  In the showcase we look for =tar= commands as I never can remember the correct arguments
  to extract an archive. We get a few hits. One of them is in a places where =tar= is used
  together with another command. But the major one was a heading about =tar= and all of
  its subsections.

  If a heading containing the command is found it shows that full section,
  including subsections.

  If a match is found in a non heading, only that section is provided.

  When you know what line you want you specify that an =sax= will return that. To be able
  to use that command I pipe it to =wl-copy=. This makes is available in my clipbord.

* Install

  Clone the repo to some place, in the examples it's cloned to: =~/git/sax=.

  Set environment variable so you can reach =sax=. Point =SAXFILE= to your org
  file.

  #+BEGIN_SRC shell :results output code
    export PATH="$PATH:$HOME/git/sax/"
    export AWKPATH="$AWKPATH:$HOME/git/sax/"
    export SAXFILE="$HOME/org-documents/shell-commands.org"
  #+END_SRC

  You may need to logout and login again to update environment variables. Or
  source your =.bashrc= using: =source ~/.bashrc=
